"""
basis_check.py — Quantify the training/benchmark LABEL-BASIS MISMATCH, and report the
model metrics that are immune to it.

WHY THIS EXISTS
---------------
The models are trained on Materials Project lattice parameters, which are DFT-RELAXED
geometry. The benchmark `a_true` columns are EXPERIMENTAL measurements. These are not the
same quantity. A large part of the benchmark "model error" is therefore not model error at
all — it is the DFT-vs-experiment discrepancy, inherited through the training labels.

Note MP's `theoretical: False` flag means "this structure has been OBSERVED", NOT "these
lattice parameters were MEASURED". Every lattice parameter in MP is computed. mp-1865 (UN)
is flagged theoretical=False and still carries a DFT geometry of 4.877379 A, against an
experimental 4.884 A.

WHAT THIS SCRIPT WILL AND WILL NOT CLAIM
----------------------------------------
It will NOT emit a DFT->experiment correction factor. That would be unprovable here:

  1. n = 3. Only three of the nine curated hosts (UN, UC, CeO2) have an experimental value
     anywhere in this repository — they are benchmark end-members. The other six (UO2, PuO2,
     ThO2, ZrO2, Nd2O3, NdO2) have NO experimental lattice parameter in-repo, so their delta
     is unknown. Filling them in from memory or from an uncited source is exactly the
     kind of claim this script refuses to make.
  2. The sign of the delta FLIPS across those three points (UN -0.006621, UC -0.022736,
     CeO2 +0.057365 A). A single global offset is therefore refuted by our own data. Their
     mean is meaningless and is deliberately not computed.
  3. The delta is not a clean "DFT error" anyway. It bundles, inseparably: exchange-correlation
     functional error; 0 K (DFT) vs ~room temperature (experiment) thermal expansion; zero-point
     motion; and any error in the experimental value itself. Attributing it to any one of these
     from three numbers is not supportable.

Instead it reports the two things that ARE provable:

  (A) ANCHOR TABLE — the exact per-material delta at the three points where both a DFT and an
      experimental value exist in-repo. Stated individually, never averaged.

  (B) BASIS-INVARIANT METRICS — a constant offset cannot change the SLOPE or the CORRELATION
      of predicted-vs-true. So slope and Pearson r measure what the model actually learned about
      composition, independent of the basis mismatch. These are the defensible model-comparison
      numbers, and they do not require the correction to exist.

CAVEAT ON INDEPENDENCE: Data/README.md records that 19 of UNUC.csv's 23 rows are sampled from
the quadratic fit to the literature values, so a_true is largely a smooth fitted curve rather
than 23 independent measurements; the other 4 rows are measured values. Correlation against it
therefore measures fidelity to that fit. CeO2Nd2O3Vals.csv has only n=7, so its slope is
correspondingly uncertain. Both are reported with their n so the reader can weigh them.

Run:  .venv/Scripts/python scripts/basis_check.py
Out:  Results/benchmarks/basis_check.md  +  Results/benchmarks/basis_check.csv
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from engine import config  # noqa: E402

# The ONLY three points where this repo holds both a DFT label and an experimental value.
# Each experimental value is cited to the exact benchmark file and row it comes from.
ANCHORS = [
    # host,   mp_id,      experimental a,  provenance of the experimental value
    ("UN",   "mp-1865",   4.884,      'Data/benchmarks/UNUC.csv, row "U1 N1"'),
    ("UC",   "mp-2489",   4.9591,     'Data/benchmarks/UNUC.csv, row "U1 C1"'),
    ("CeO2", "mp-20194",  5.410085,   'Data/benchmarks/CeO2Nd2O3Vals.csv, row "Ce1 O2"'),
]

BENCHMARKS = {
    "UNUC":      "U(N,C)",
    "CeO2Nd2O3": "(Ce,Nd)O2",
}


def main() -> int:
    seed = pd.read_csv(config.dataset_original(), low_memory=False)
    refs = json.loads((config.REFERENCE_SYSTEMS).read_text(encoding="utf-8"))

    def dft_a(mp_id: str) -> float | None:
        row = seed[seed.material_id == mp_id]
        return float(row.a.iloc[0]) if len(row) else None

    lines: list[str] = []
    csv_rows: list[dict] = []
    w = lines.append

    w("# Basis check: DFT training labels vs experimental benchmark labels")
    w("")
    w("GENERATED by `scripts/basis_check.py`. Do not hand-edit.")
    w("")
    w("The models are trained on Materials Project DFT-relaxed lattice parameters.")
    w("The benchmark `a_true` columns are experimental. These are different quantities,")
    w("so part of every benchmark error is basis mismatch, not model error.")
    w("")
    w("MP's `theoretical: False` means the structure has been observed, not that the")
    w("lattice parameters were measured. All MP lattice parameters are computed.")
    w("")

    # ---------------- (A) anchor table ----------------
    w("## (A) Anchor table")
    w("")
    w("These are the only materials for which this repository holds both a DFT value and an")
    w("experimental value. Every other curated host has no in-repo experimental value, so its")
    w("delta is unknown and is reported as such rather than estimated.")
    w("")
    w("| host | mp-id | DFT a (Å) | experimental a (Å) | delta = DFT − exp (Å) | experimental value from |")
    w("|---|---|---|---|---|---|")
    for host, mp_id, exp_a, prov in ANCHORS:
        d = dft_a(mp_id)
        if d is None:
            continue
        delta = d - exp_a
        w(f"| {host} | `{mp_id}` | {d:.6f} | {exp_a:.6f} | {delta:+.6f} | {prov} |")
        csv_rows.append({
            "kind": "anchor", "host": host, "mp_id": mp_id,
            "dft_a_angstrom": d, "experimental_a_angstrom": exp_a,
            "delta_dft_minus_exp_angstrom": delta, "experimental_source": prov,
        })
    w("")
    w("Hosts with no in-repo experimental value, whose delta is unknown and not estimated:")
    w("")
    w("| host | mp-id | DFT a (Å) | experimental a | delta |")
    w("|---|---|---|---|---|")
    anchored = {h for h, _, _, _ in ANCHORS}
    for host, meta in refs.items():
        if host in anchored:
            continue
        d = dft_a(meta["mp_id"])
        ds = f"{d:.6f}" if d is not None else "not in seed"
        w(f"| {host} | `{meta['mp_id']}` | {ds} | none in repo | unknown |")
        csv_rows.append({
            "kind": "unanchored", "host": host, "mp_id": meta["mp_id"],
            "dft_a_angstrom": d, "experimental_a_angstrom": None,
            "delta_dft_minus_exp_angstrom": None,
            "experimental_source": "NONE IN REPO, delta unknown",
        })
    w("")
    w("### Why no correction factor is shipped")
    w("")
    w("1. n = 3. Three anchors cannot define a correction over a 64,128-row training domain.")
    w("2. The sign flips: UN −0.006621, UC −0.022736, CeO2 +0.057365. A single global offset is")
    w("   contradicted by these three points, so their mean is not computed.")
    w("3. The delta is not attributable. It bundles exchange-correlation functional error, 0 K")
    w("   (DFT) against finite-temperature (experiment) thermal expansion, zero-point motion,")
    w("   and error in the experimental value itself. Three numbers cannot separate four causes.")
    w("")
    w("### The temperature confound")
    w("")
    w("DFT relaxes at 0 K, without zero-point motion. The experimental values are measured at some")
    w("T > 0, and for UN at a temperature the source does not state (COD 9008757, Wyckoff")
    w("*Crystal Structures* 1963, carries no `_cell_measurement_temperature`). Every material")
    w("expands on heating, so `a_exp(T) > a_exp(0 K)`, and:")
    w("")
    w("```")
    w("DFT − a_exp(0K)  =  [DFT − a_exp(T)]  +  [a_exp(T) − a_exp(0K)]")
    w("                 =   measured delta   +   a strictly positive term")
    w("```")
    w("")
    w("The same-temperature delta is therefore more positive than the measured delta, which")
    w("determines which of the three anchors can be relied on:")
    w("")
    w("| anchor | measured delta | same-temperature delta | status |")
    w("|---|---|---|---|")
    w("| CeO2 | +0.057365 | more positive still | holds; DFT exceeds experiment |")
    w("| UN | −0.006621 | less negative, possibly positive | sign undetermined |")
    w("| UC | −0.022736 | less negative, possibly positive | sign undetermined |")
    w("")
    w("A thermal-expansion term on a ~4.9 Å cell over a few hundred K is plausibly the same order")
    w("as the UN and UC deltas. The CeO2 result therefore stands, and with it the explanation for")
    w("the uniform over-prediction on (Ce,Nd)O2, but the claim that DFT under-estimates UN and UC")
    w("does not follow. That would require a cited thermal-expansion coefficient, which this")
    w("repository does not hold. Only the sign of the correction is known, not its magnitude.")
    w("")
    w("### What a calibration reference would need")
    w("")
    w("Per entry, checked against a candidate (COD 9008757, UN), which fails 3 of 6:")
    w("")
    w("| # | Requirement | COD 9008757 |")
    w("|---|---|---|")
    w("| 1 | `_cell_measurement_temperature`, mandatory | absent |")
    w("| 2 | standard uncertainty on `_cell_length_a` (`4.884(2)`) | bare `4.884` |")
    w("| 3 | measured stoichiometry (UN₁₋ₓ / UO₂₊ₓ, since `a` depends strongly on O/M) | just \"UN\" |")
    w("| 4 | primary diffraction source, not a compilation | Wyckoff 1963 textbook tabulation |")
    w("| 5 | spacegroup matches the MP entry | yes, Fm-3m (225) = mp-1865 |")
    w("| 6 | conventional-cell setting | yes, Z=4, a = 4.884 Å |")
    w("")
    w("`_cell_length_a` = 4.884 Å in that CIF is `UNUC.csv`'s `a_true` for `U1 N1` exactly, so the")
    w("benchmark is likely built on that same 1963 value and inherits its missing temperature and")
    w("missing uncertainty. It is not an independent check on this problem.")
    w("")
    w("Per set: N large enough to fit and hold out, dozens rather than 3; spanning the training")
    w("domain rather than fuels alone; every entry matched to a specific MP `material_id` with the")
    w("same spacegroup and composition; the calibration expressed as a learned map (DFT a → exp a")
    w("at a reference T, with structure and composition features) rather than a single scalar,")
    w("which the sign flip across these three points already rules out; and held-out validation")
    w("reporting residual and CI. ICSD records temperature more consistently than COD and would be")
    w("the better source.")
    w("")

    # ---------------- (B) basis-invariant metrics ----------------
    w("## (B) Basis-invariant model metrics")
    w("")
    w("A constant offset cannot change the slope or the correlation of predicted against true, so")
    w("these measure what each model learned about composition and stay valid whatever the")
    w("DFT/experiment delta turns out to be.")
    w("")
    w("`bias` is the mean signed error (the offset). `scatter` is the std of the error after")
    w("removing that bias, i.e. how well the model tracks the trend once the offset is gone.")
    w("")
    for name, system in BENCHMARKS.items():
        pred_path = REPO / "Results" / "benchmarks" / name / "predictions.csv"
        if not pred_path.exists():
            w(f"### {system}, `{name}`: not run (no predictions.csv)")
            w("")
            continue
        df = pd.read_csv(pred_path)
        if "a_true" not in df.columns:
            continue
        w(f"### {system}, `{name}` (n = {len(df)})")
        w("")
        w("| model | MAE vs exp (Å) | bias (Å) | scatter (Å) | slope | Pearson r |")
        w("|---|---|---|---|---|---|")
        for key in config.SCOREABLE:
            col = f"a_pred_{key}"
            if col not in df.columns:
                continue
            valid = df[["a_true", col]].dropna()
            if len(valid) < 2:
                continue
            t = valid["a_true"].to_numpy()
            p = valid[col].to_numpy()
            e = p - t
            slope = float(np.polyfit(t, p, 1)[0])
            r = float(np.corrcoef(t, p)[0, 1])
            nm = config.MODEL_FILES[key][1]
            w(f"| {nm} (`{key}`) | {np.abs(e).mean():.6f} | {e.mean():+.6f} | "
              f"{e.std(ddof=0):.6f} | {slope:.3f} | {r:.4f} |")
            csv_rows.append({
                "kind": "metric", "benchmark": name, "system": system, "n_rows": len(valid),
                "model_key": key, "model_name": nm,
                "MAE_vs_exp_angstrom": float(np.abs(e).mean()),
                "bias_angstrom": float(e.mean()),
                "scatter_angstrom": float(e.std(ddof=0)),
                "slope": slope, "pearson_r": r,
            })
        w("")

    w("### Reading these")
    w("")
    w("- MAE vs exp is not pure model error, because it contains the basis mismatch. Do not quote")
    w("  it as \"the model is wrong by X Å\" without saying what it is compared against.")
    w("- Slope and Pearson r are the comparison to use. A model with a large bias but slope ≈ 1")
    w("  and r ≈ 1 has learned the composition dependence and is offset. A model with small bias")
    w("  but r ≈ 0 has learned nothing and lands near the right answer by coincidence.")
    w("")
    w("Independence caveat: `Data/README.md` records that 19 of UNUC.csv's 23 rows are sampled")
    w("from the quadratic fit to the literature values, so `a_true` there is largely a fitted")
    w("curve rather than 23 independent measurements, and correlation against it measures")
    w("fidelity to that fit. CeO2Nd2O3Vals.csv has n = 7, so its slope carries real")
    w("uncertainty. Weigh both by their n.")
    w("")

    out_dir = REPO / "Results" / "benchmarks"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "basis_check.md").write_text("\n".join(lines), encoding="utf-8")
    pd.DataFrame(csv_rows).to_csv(out_dir / "basis_check.csv", index=False)
    print(f"wrote {out_dir / 'basis_check.md'}")
    print(f"wrote {out_dir / 'basis_check.csv'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
